# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    reviewers:
      - "lizzcondrey"
    labels:
      - "security"
      - "dependencies"
    versioning-strategy: increase
    groups:
       # Specify a name for the group, which will be used in pull request titles
       # and branch names
      doc-dependencies:
        applies-to: version-updates
        patterns:
          - "sphinx*"
          - "docutils"
          - "myst-parser"
          - "pytz"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "lizzcondrey"
    labels:
      - "security"
      - "dependencies"
    groups:
      workflows:
        applies-to: version-updates
        patterns:
          - "actions/*"
