on:
  workflow_call:

defaults:
  run:
    working-directory: ./python

jobs:
  build_python_artifacts:
    name: Build Artifacts
    runs-on: ubuntu-22.04
    outputs:
      version_string:
        description: "Package version"
        value: ${{ steps.aac-version.outputs.version_string }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install the AaC Package
        run: pip install aac -e .[all]

      - name: Lint with flake8
        run: flake8 .

      - name: List Transitive Dependencies
        run: pipdeptree

      - name: Build distribution package
        run: python setup.py bdist_wheel

      - name: Get Package Version
        id: aac-version
        run: python -m aac version

      - name: Upload Python Wheel
        uses: actions/upload-artifact@v4
        with:
          name: aac_${{steps.aac-version.outputs.version_string}}_wheel
          path: python/dist/

      - name: Build Documentation
        run: |
          cp -R ../docs/ ./docs
          cd ./docs
          sphinx-build source doc_artifacts

      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: aac_${{steps.aac-version.outputs.version_string}}_documentation
          path: |
            python/docs/doc_artifacts/api
            python/docs/doc_artifacts/project_documentation

      - name: Build PDF
        run: |
          make -C ../docs/ simplepdf

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: aac_${{steps.aac-version.outputs.version_string}}_documentation_pdf
          path: |
            docs/docs/simplepdf/Architecture-as-Code.pdf
